[package]
name = "ordinary-data"
version = "0.0.1"
authors = ["Erxl <sermelt@126.com>"]
edition = "2018"
readme = "README.md"
license = "Mulan PSL v2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
counting-pointer = "0.1.0"